{% set version = "3.6.1" %}

package:
  name: sleef
  version: {{ version }}

source:
  url: https://github.com/shibatch/sleef/archive/{{ version }}.tar.gz
  sha256: 441dcf98c0f22e5d5e553d007f3b93e89eb58e4c66e340da8af5e7f67d1dc24c

build:
  number: 3
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('sleef', max_pin='x') }}
  skip: true  # [win and vc<14]
  ignore_run_exports_from:
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja        # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - openssl
    - llvm-openmp  # [osx]

test:
  commands:
    - test -f $PREFIX/include/sleef.h                          # [unix]
    - test -f $PREFIX/lib/libsleef${SHLIB_EXT}                 # [unix]
    - test -f $PREFIX/lib/libsleefquad${SHLIB_EXT}             # [linux]
    - test -f $PREFIX/include/sleefquad.h                      # [linux]
    - if not exist %PREFIX%\\Library\\include\\sleef.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\sleefquad.h exit 1  # [win]

about:
  home: https://sleef.org/
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: SIMD library for evaluating elementary functions

extra:
  recipe-maintainers:
    - bluescarni
